### ISSUE TITLE
Quick question about registration

### ISSUE THREAD

**Issue by ConorOW** [MASILab/Synb0-DISCO#10]
Hey everyone,

We were wondering if there was a reason to input the T1/b0 that have been linearly registered to the template over the nonlinear outputs of 'prepare_input.sh'?

Also, if we understand correctly, the model you all trained works better on images with skull?

Thanks heaps,
Conor

**Comment by hanscol** [comment]
For the registration, we wanted the model to rely as little as possible on accurate registration, so we decided to preserve the anatomy and require the model be robust to this. 

Something the model may not be robust to is images without skulls, because the training set only included images with a skull.

**Comment by ConorOW** [comment]
Thank you so much for explaining that Colin, I really appreciate it!
