### ISSUE TITLE
Problem with FSLs BET inside SynB0

### ISSUE THREAD

**Issue by j-gerb** [MASILab/Synb0-DISCO#13]
Dear experts,

I encountered some problems where BET crops away most of the brain on my T1, leaving only parts of the cerebellum and a lot of neck tissue. This obviously leads to quite bad end-results.

Running BET without the -R flag directly from command line works way better, but I don't see an option to tell SynB0 (I run the docker version) to just use BET. Is there a way to give extra parameters or to modify this step?

If this is not possible, I will just manually crop my T1 so that BET hopefully doesn't run into this problem, it wouldn't be much extra work. 

Thanks in advance!

Best, 
Johannes

**Comment by hanscol** [comment]
Hello Johannes,

We decided the easiest solution would be to allow users to optionally provide their own mask. I've updated the source code as well as the docker, so that you can provide a file in your inputs folder named T1_mask.nii.gz. The code will simply skip the BET step and use this for further processing. 

If you have any questions or encounter any further issues, please let us know.

Best,
Colin

**Comment by j-gerb** [comment]
Dear Colin,

Thanks a lot for the quick and helpful reply, this will be very useful.

All the best,
Johannes
