### ISSUE TITLE
Missing dual_channel_unet ?

### ISSUE THREAD

**Issue by abesik** [MASILab/Synb0-DISCO#28]
Hi there! We've been having issues getting synb0 to work using docker / podman (we're using CentOS 7 on IT managed computers with our users existing on a server we have no permission to access so running rootless is.. painful to say the least). So for the meantime I've been trying to go through the pipeline.sh script to configure this to work without using a container.

I'm basically trying to replicate the paths in a working directory set up the same way it is expected to be in the container, on my local computer - but I came across  /extra/dual_channel_unet  on line 40 of pipeline.sh and can't seem to locate this in any of the folders cloned from git.

Is this something I should have in my manually created /extra directory, or is this something python/pytorch creates automatically? 

I appreciate your time and help!

**Comment by psimonjones** [comment]
Thanks for SynBo-DISCO. I have a similar question.

I have obtained some nice-looking results using Synb0_DSICO.

However, the file pipeline.sh has the parameter
/extra/dual_channel_unet/num_fold_"$i"_total_folds_"$NUM_FOLDS"_seed_1_num_epochs_100_lr_0.0001_betas_\(0.9\,\ 0.999\)_weight_decay_1e-05_num_epoch_*.pth
The src directory released contains 'train_lin' but not 'dual_channel_unet'. I renamed 'train_lin' 'dual_channel_unet' so that the script would run without error. Is that OK or are the files inside 'train_lin' wrong?

Thanks for your help

**Comment by psimonjones** [comment]
I had a look at the files inside the Singularity container synb0_latest.sif and there is a directory called /extra/dual_channel_unet with pth files inside it that are identical to the pth files in /src/train_lin so I guess renaming it dual_channel_unet won't be worse than using the Singularity container.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
