### ISSUE TITLE
Failure in distortion correction 

### ISSUE THREAD

**Issue by lbinding** [MASILab/Synb0-DISCO#56]
Hi all, 

Long-time fan and user of your work. I've noticed on some cases distortion correction seems to fail, see the images for examples. I've checked the T1 registration and it looks good so I can't see any immediate reason for this. Have you encountered anything like this before? 

Thanks! 

All the best, 
Lawrence 
<img width="600" alt="Screenshot 2023-11-03 at 09 27 26" src="https://github.com/MASILab/Synb0-DISCO/assets/34344594/cdc463b9-dd61-4f35-af1a-3d60b39f57a1">
<img width="586" alt="Screenshot 2023-11-03 at 09 28 23" src="https://github.com/MASILab/Synb0-DISCO/assets/34344594/6f0d1525-1fb4-41b4-ba1d-7fc36fb46d68">
<img width="599" alt="Screenshot 2023-11-03 at 09 27 56" src="https://github.com/MASILab/Synb0-DISCO/assets/34344594/5b9531d6-9606-440a-8a17-c3d1f427e1f2">

**Comment by lbinding** [comment]
Hi, I've worked out the issue. Its an issue with registering to the atlas so I've modified the code to work with niftyReg and easyReg which typically have more consistent registration than ANTs. Happy to share the code if you want!

**Comment by schillkg** [comment]
Hi Lawrence - thank you for the message. 

My original guess would have been a poor mask within the pipeline. We use FSL's 'bet' which doesn't need to be perfect but still requires something close in order to align b=0 to T1. If this failed it would cause a registration issue.

Based on your last message I'm guessing its an issue with T1 to MNI? I think we would be happy to include a niftyReg or similar registration if you believe it to be more robust. We could likely add a flag for alternative registration. 

We also hope to get a more robust masking procedure in the near feature (SynthStrip, etc). 

Thank you again.
