### ISSUE TITLE
Bizarre synthesized output

### ISSUE THREAD

**Issue by araikes** [MASILab/Synb0-DISCO#64]
Hi  @schillkg,

I'm hoping you can help me out. I'm processing a large dataset where most of the individuals and sessions do not have a reverse-phase encoded diffusion acquisition. Synb0-DISCO works great for the majority of them. However, for some individuals, I get and output like the following 

![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/62e54deb-8a57-46e0-a815-ba8a8fefc179)

I've checked the input T1, the distorted b0, and the registration between the T1 and MNI and none have this kind of weirdness (see below). However, all of the `b0_u_lin_atlas_*` files have this kind of issue. Do you have any thoughts/suggestions on what the problem might be and how to fix it?

Thanks

T1w:
![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/052edf91-a2b4-4eab-b636-f9d627936e8c)

T1w_norm_non_atlas_2_5
![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/8b1f0092-d5a8-469a-ab9b-c73e4dc5ef60)

b0
![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/60d56707-d9ad-4f72-be67-d2f1a92b7ab6)

b0_d_nonlin_atlas_2_5
![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/ee8383e2-e12a-4f00-97c3-40be9c8e4375)

b0_u_lin_atlas_2_5_FOLD_1
![image](https://github.com/MASILab/Synb0-DISCO/assets/18663624/26c0ae2c-4eee-40c8-9034-ed003c60d93f)

**Comment by schillkg** [comment]
Hi @araikes  - hope I can help debug!

A few questions: 

First (this probably isn't the issue), was the T1 pre-processed in any way? Some denoising algorithms, and even FreeSurfer pre-processing, have caused failures in the registration process we use in the pipeline.

The second question we ask is "is the synthetic b0 reasonable?". The answer to this, in your data, is NO! The synthesis failed quite miserably. Could you show me what T1_norm_lin_atlas_2_5.nii.gz and b0_d_lin_atlas_2_5.nii.gz look like? Note the "lin" instead of "nonlin". We use the "lin" for synthesis. Here, we want to be sure that they are not only aligned with each other, but also are roughly oriented and aligned with MNI152. Based on the "nonlin" screen grabs above, I'm going to guess the "lin" are not aligned. This means either the b0 to T1 registration failed, or the T1 to MNI alignment failed. I'm guessing the former (which usually happens because of preprocessed T1s!). 

If this failed, and if the T1 was indeed not processed in any way, could you try skull stripping the T1 and running the pipeline with the "--stripped" flag?

Thank you - this greatly helps us debug - and if this is a registration issue we hope to make this much more robust (and lightweight) in future iterations.

Kurt
